### ISSUE TITLE
Sweeping failed

### ISSUE THREAD

**Issue by rasos** [FairCoinTeam/faircoin-wallet#1]
Tried to sweep from a paper wallet. App hangs with "Aktualisiere Guthaben" and did not transfer it when restarting it.
Has the swipe feature been adapted for the FairCoin Android wallet? 
https://github.com/FairCoinTeam/faircoin-wallet/tree/prod/wallet says, that it is looking for unspent addresses here: https://api.biteasy.com/blockchain/v1/unspent-outputs - which blockchain is that?

**Comment by thokon00** [comment]
Sweeping is not implemented in this version. It will however be implemented in the new android wallet for FairCoin2. But this is a different project and will reside under the new 'organization': https://github.com/faircoin
